---

# Docker
docker_users:
  - azureuser

# Keycloak
keycloak_admin_user: admin
keycloak_admin_password: ChangeMe123!

keycloak_db_name: keycloak
keycloak_db_user: keycloak
keycloak_db_password: KeycloakDBPass123!

# Networking
keycloak_hostname: "{{ ansible_host }}"

# Project directory
app_directory: /opt/keycloak-stack
