name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible and Python dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip

      - name: Install Ansible Docker collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IAM_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 20.165.186.196 >> ~/.ssh/known_hosts

      - name: Wait for SSH
        run: sleep 30

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml \
          -i "20.165.186.196," \
          -u ${{ secrets.VM_USER }} \
          --private-key ~/.ssh/id_rsa
