name: Test Azure SSH

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IAM_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM to known hosts
        run: |
          ssh-keyscan -H "20.165.186.196" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa \
          -o StrictHostKeyChecking=no \
          ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "echo SSH CONNECTION SUCCESS"
